#!/usr/bin/env bash
bash ../install.sh
bash IMR_mem_inj_mem_rec.sh
bash IMR_mem_inj_non_mem_rec.sh
bash IMR_non_mem_inj_non_mem_rec.sh
bash IMR_non_mem_inj_mem_rec.sh
bash IMR_pure_mem_inj_pure_mem_rec.sh
#bash NRSur_mem_inj_mem_rec.sh
#bash NRSur_mem_inj_non_mem_rec.sh